[project]
enable_telemetry = true
user_env = []
session_timeout = 3600
user_session_timeout = 1296000
cache = false
allow_origins = ["*"]

[features]
unsafe_allow_html = false
latex = false
user_message_autoscroll = true
auto_tag_thread = true
edit_message = true

[features.spontaneous_file_upload]
enabled = true
accept = ["application/pdf", "image/png", "image/jpeg"]
max_files = 10
max_size_mb = 50

[UI]
name = "Solution Bot"
cot = "full"

[meta]
generated_by = "2.5.5"
